
package user_interface;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import classes.museos;
import classes.DBConsults.museosConsult;
import java.util.ArrayList;
import javax.swing.JFrame;
/**
 *
 * @author LENOVO
 */
public class firstWindow extends javax.swing.JFrame{
    
    

    /**
     * Constructor
     */
    public firstWindow() {
        
        initComponents();
        
        
        
        //Properties
        setSize(400,450);
        setResizable(false);
        setTitle("Ministerio de Cultura - Museos");
        setLocationRelativeTo(null);
        
        //Modifying the background
        ImageIcon background = new ImageIcon("src/images/background2.png");
        Icon icono = new ImageIcon(background.getImage().getScaledInstance(jlabel_background1.getWidth(),
                jlabel_background1.getHeight(), Image.SCALE_DEFAULT));
        jlabel_background1.setIcon(icono);
        this.repaint();
        
        ImageIcon background_logo = new ImageIcon("src/images/minCultura.png");
        Icon icon_logo = new ImageIcon(background_logo.getImage().getScaledInstance(jLabel_Logo.getWidth(),
                jLabel_Logo.getHeight(),Image.SCALE_DEFAULT));
        jLabel_Logo.setIcon(icon_logo); 
        this.repaint();
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/escudoIcon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Logo = new javax.swing.JLabel();
        jLabel1_select = new javax.swing.JLabel();
        jComboBox1_selectMuseum = new javax.swing.JComboBox<>();
        jButton_mainButton = new javax.swing.JButton();
        jButton_login = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jlabel_background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 129));

        jLabel1_select.setBackground(new java.awt.Color(222, 222, 222));
        jLabel1_select.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1_select.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_select.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_select.setText("Seleccione el museo que desea consultar:");
        getContentPane().add(jLabel1_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jComboBox1_selectMuseum.setBackground(new java.awt.Color(250, 250, 250));
        jComboBox1_selectMuseum.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1_selectMuseum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jComboBox1_selectMuseum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_selectMuseumActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1_selectMuseum, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 240, -1));

        jButton_mainButton.setBackground(new java.awt.Color(255, 255, 255));
        jButton_mainButton.setForeground(new java.awt.Color(0, 0, 0));
        jButton_mainButton.setText("Actualizar Lista");
        jButton_mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mainButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jButton_login.setBackground(new java.awt.Color(255, 255, 255));
        jButton_login.setForeground(new java.awt.Color(0, 0, 0));
        jButton_login.setText("Ingresar");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 270, 100, -1));

        jButton_Exit.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Exit.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Exit.setText("Salir");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jlabel_background1.setBackground(new java.awt.Color(255, 255, 255));
        jlabel_background1.setForeground(new java.awt.Color(0, 0, 0));
        jlabel_background1.setToolTipText("");
        jlabel_background1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jlabel_background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1_selectMuseumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_selectMuseumActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jComboBox1_selectMuseum ){
            if(jComboBox1_selectMuseum.getSelectedIndex()>=0){                
                System.out.println("Si sirveeee el combobox");
                String comboText = (String)jComboBox1_selectMuseum.getSelectedItem();                
            }
        }      
        
    }//GEN-LAST:event_jComboBox1_selectMuseumActionPerformed
    //Update List Button
    private void jButton_mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mainButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jButton_mainButton ){
            System.out.println("Si sirveeee el button");
            consultMuseos();
        }  
    }//GEN-LAST:event_jButton_mainButtonActionPerformed
    //Login to Museum view
    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
        
        /*secondWindow sw = new secondWindow(){
            @Override
            public void dispose(){
                getFrame().setVisible(true);
                super.dispose();
            }
        };
        
        sw.setVisible(true);
        dispose();*/
        
        if (evt.getSource () == jButton_login){              
            new secondWindow().setVisible(true);
            this.dispose();
            String comboText = (String)jComboBox1_selectMuseum.getSelectedItem(); 
                       
        }
        
    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:        
        System.exit(0);
    }//GEN-LAST:event_jButton_ExitActionPerformed
    
    //Method to get the JFrame of this window
    private JFrame getFrame(){        
        return this;
    }
    private void consultMuseos(){
        jComboBox1_selectMuseum.removeAllItems();        
        museosConsult mis_museos = new museosConsult();
        ArrayList<museos> mis_museosList = mis_museos.consultMuseos();
        
        for(int i = 0; i <  mis_museosList.size();i++){
            jComboBox1_selectMuseum.addItem(mis_museosList.get(i).getId()+" - "+mis_museosList.get(i).getNombre());
        }
        System.out.println("Estas en ConsulMuseos");
        
    };
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_login;
    private javax.swing.JButton jButton_mainButton;
    private javax.swing.JComboBox<String> jComboBox1_selectMuseum;
    private javax.swing.JLabel jLabel1_select;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jlabel_background1;
    // End of variables declaration//GEN-END:variables
}

