/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author LENOVO
 */
public class valueWindow extends javax.swing.JFrame {

    /**
     * Creates new form valueWindow
     */
    public valueWindow() {
        initComponents();
        setTitle("Valores");
        setLocationRelativeTo(null);
        
        //Modifying var
        jTextField_Value.setEditable(false);
        
        
        /*Modifying the background
        ImageIcon background = new ImageIcon("src/images/background2.png");
        Icon icono = new ImageIcon(background.getImage().getScaledInstance(jLabel_Title.getWidth(),
                jLabel_Title.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Title.setIcon(icono);
        this.repaint();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_filterValue = new javax.swing.JComboBox<>();
        jLabel_Title = new javax.swing.JLabel();
        jButton_showData = new javax.swing.JButton();
        jButton_return = new javax.swing.JButton();
        jTextField_Value = new javax.swing.JTextField();
        jLabel_background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox_filterValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Avalúo total", "Avalúo por artista" }));
        jComboBox_filterValue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_filterValueItemStateChanged(evt);
            }
        });
        jComboBox_filterValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_filterValueActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_filterValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel_Title.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(102, 0, 51));
        jLabel_Title.setText("Valor de nuestras pinturas");
        getContentPane().add(jLabel_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 340, -1));

        jButton_showData.setText("Mostrar");
        jButton_showData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_showDataActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_showData, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jButton_return.setText("Regresar");
        jButton_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_returnActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        jTextField_Value.setForeground(new java.awt.Color(102, 0, 51));
        jTextField_Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ValueActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Value, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 290, 60));
        getContentPane().add(jLabel_background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_filterValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_filterValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_filterValueActionPerformed

    private void jButton_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_returnActionPerformed
        // TODO add your handling code here:
        new secondWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_returnActionPerformed

    private void jButton_showDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_showDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_showDataActionPerformed

    private void jTextField_ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ValueActionPerformed

    private void jComboBox_filterValueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_filterValueItemStateChanged
        // TODO add your handling code here:
        String value = jComboBox_filterValue.getSelectedItem().toString();
        if(value.equals("Avalúo total")){
            jTextField_Value.setBackground(Color.getHSBColor(99, 4, 75));
            jTextField_Value.setText("$150.500.000.000");            
        }else if(value.equals("Avalúo por artista")){
            jTextField_Value.setBackground(Color.getHSBColor(99, 4, 75));
            jTextField_Value.setText("$1.500.000.000");            
        }else{
            jTextField_Value.setText("");
        }
            
            
    }//GEN-LAST:event_jComboBox_filterValueItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(valueWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(valueWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(valueWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(valueWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new valueWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_return;
    private javax.swing.JButton jButton_showData;
    private javax.swing.JComboBox<String> jComboBox_filterValue;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_background1;
    private javax.swing.JTextField jTextField_Value;
    // End of variables declaration//GEN-END:variables
}
